"""
Sets the `article` column for Spanish nouns.
ONLY updates the `article` column. Does NOT touch word, translation, 
next_review, interval, repetitions, ease_factor, is_ignored, or any other column.
"""
import sqlite3

DB_FILE = "vocab.db"

# Manually classified articles for all nouns in the database.
# Format: "word": "el" or "la"
# Words not in this dict are not nouns (verbs, adjectives, adverbs, etc.)
ARTICLES = {
    # ---- EL (masculine) ----
    "hombre": "el",
    "disparo": "el",
    "charco": "el",
    "ojo": "el",
    "atraco": "el",
    "trabajo": "el",
    "segurata": "el",
    "ladrón": "el",
    "asesino": "el",
    "día": "el",
    "año": "el",
    "viejecito": "el",
    "cuerpo": "el",
    "alma": "el",  # el alma (f, but uses el)
    "tono": "el",
    "tiempo": "el",
    "teléfono": "el",
    "niño": "el",
    "cariño": "el",
    "viaje": "el",
    "barco": "el",
    "chino": "el",
    "cocinero": "el",
    "billete": "el",
    "cementerio": "el",
    "mercado": "el",
    "matadero": "el",
    "ángel": "el",
    "guarda": "el",
    "minuto": "el",
    "plato": "el",
    "momento": "el",
    "camino": "el",
    "equipo": "el",
    "coche": "el",
    "profesor": "el",
    "culo": "el",
    "furgón": "el",
    "campo": "el",
    "diamante": "el",
    "tiburón": "el",
    "jefe": "el",
    "mando": "el",
    "asalto": "el",
    "tosido": "el",
    "amor": "el",
    "negocio": "el",
    "palo": "el",
    "periódico": "el",
    "ruido": "el",
    "mes": "el",
    "golpe": "el",
    "sueldo": "el",
    "caso": "el",
    "nombre": "el",
    "número": "el",
    "planeta": "el",  # exception: el planeta
    "rollo": "el",
    "señor": "el",
    "registro": "el",
    "DNI": "el",
    "efecto": "el",
    "fantasma": "el",
    "dinero": "el",
    "héroe": "el",
    "cuidado": "el",
    "timbre": "el",
    "miedo": "el",
    "atracador": "el",
    "zombi": "el",
    "esqueleto": "el",
    "bigote": "el",
    "pintor": "el",
    "cojón": "el",
    "muñeco": "el",
    "ratón": "el",
    "guantazo": "el",
    "lado": "el",
    "crío": "el",
    "papa": "el",  # el papa (pope) vs la papa (potato)
    "santo": "el",
    "frenazo": "el",
    "zapato": "el",
    "segundo": "el",
    "artefacto": "el",
    "arsenal": "el",
    "camión": "el",
    "edificio": "el",
    "papel": "el",
    "fusil": "el",
    "cuello": "el",
    "valor": "el",
    "heroísmo": "el",
    "precio": "el",
    "uniforme": "el",
    "camionero": "el",
    "cambio": "el",
    "caos": "el",
    "chico": "el",
    "cordero": "el",
    "culatazo": "el",
    "error": "el",
    "favor": "el",
    "macho": "el",
    "matrimonio": "el",
    "mensaje": "el",
    "móvil": "el",
    "museo": "el",
    "riñón": "el",
    "vestíbulo": "el",
    "poquito": "el",
    "llanto": "el",
    "pin": "el",
    "ahogo": "el",
    "crack": "el",
    "lujo": "el",
    "metal": "el",
    "monstruo": "el",
    "paso": "el",
    "salvoconducto": "el",
    "asado": "el",
    "papá": "el",
    "talego": "el",
    "currículum": "el",
    "sitio": "el",
    "cerebro": "el",
    "remedio": "el",
    "don": "el",
    "sistema": "el",  # exception: el sistema
    "Oscar": "el",
    "idioma": "el",  # exception: el idioma
    "limbo": "el",
    "tío": "el",
    "compromiso": "el",
    "anillo": "el",
    "pedruscazo": "el",
    "principio": "el",
    "agente": "el",
    "apoyo": "el",
    "corazón": "el",
    "fuego": "el",
    "suelo": "el",
    "trueno": "el",
    "sonido": "el",
    "ordenador": "el",
    "plan": "el",
    "resto": "el",
    "rey": "el",
    "sol": "el",
    "chaleco": "el",
    "cine": "el",
    "bocajarro": "el",  # a bocajarro (point-blank)

    # ---- LA (feminine) ----
    "mujer": "la",
    "historia": "la",
    "vez": "la",
    "sangre": "la",
    "profesión": "la",
    "manera": "la",
    "foto": "la",
    "comisaría": "la",
    "cámara": "la",
    "llamada": "la",
    "cosa": "la",
    "realidad": "la",
    "mamá": "la",
    "noticia": "la",
    "tortilla": "la",
    "tontería": "la",
    "calle": "la",
    "ciencia": "la",
    "ventaja": "la",
    "gente": "la",
    "policía": "la",
    "pistola": "la",
    "pelota": "la",
    "relación": "la",
    "casa": "la",
    "madre": "la",
    "opinión": "la",
    "parte": "la",
    "víctima": "la",
    "fábrica": "la",
    "moneda": "la",
    "careta": "la",
    "peli": "la",
    "muerte": "la",
    "arma": "la",  # el arma (f, but uses el before singular)
    "mano": "la",  # exception: la mano
    "oreja": "la",
    "razón": "la",
    "punta": "la",
    "peña": "la",
    "carnicería": "la",
    "banda": "la",
    "boda": "la",
    "décima": "la",
    "tonelada": "la",
    "bobina": "la",
    "cocina": "la",
    "sirena": "la",
    "posibilidad": "la",
    "radio": "la",  # la radio (broadcast)
    "telefonía": "la",
    "cabeza": "la",
    "puerta": "la",
    "hija": "la",
    "marca": "la",
    "agua": "la",  # el agua (f, but uses el before singular)
    "clase": "la",
    "fachada": "la",
    "mitad": "la",
    "niña": "la",
    "noche": "la",
    "rueda": "la",
    "tranquilidad": "la",
    "voz": "la",
    "profesora": "la",
    "acreditación": "la",
    "visita": "la",
    "respiración": "la",
    "izquierda": "la",
    "pareja": "la",
    "fecundación": "la",
    "fertilidad": "la",
    "pensión": "la",
    "prueba": "la",
    "paternidad": "la",
    "escalera": "la",
    "idea": "la",
    "sensación": "la",
    "persona": "la",
    "forma": "la",
    "disculpa": "la",
    "cara": "la",
    "boca": "la",
    "frente": "la",
    "pieza": "la",
    "cama": "la",
    "cárcel": "la",
    "suerte": "la",
    "cafetería": "la",
    "interpretación": "la",
    "comunicación": "la",
    "radiofrecuencia": "la",
    "paz": "la",
    "tormenta": "la",
    "corriente": "la",
    "mañana": "la",
    "edad": "la",
    "carretilla": "la",
    "chapa": "la",
    "pedida": "la",
    "película": "la",
    "seguridad": "la",
    "bolsa": "la",
    "cuenta": "la",
    "emisora": "la",
    "bala": "la",
    "milésima": "la",
    "rata": "la",
    "velocidad": "la",
    "puta": "la",
    "risa": "la",
    "oferta": "la",
    "gracia": "la",
    "bienvenida": "la",
    "mierda": "la",
    "pregunta": "la",
    "ciudad": "la",
    "señorita": "la",
    "rima": "la",
    "busca": "la",
    "captura": "la",
    "joyería": "la",
    "subasta": "la",
    "piscina": "la",
    "mina": "la",
    "peletería": "la",
    "relojería": "la",
    "caja": "la",
    "lanza": "la",
    "herramienta": "la",
    "droga": "la",
    "costilla": "la",
    "pelea": "la",
    "discoteca": "la",
    "bomba": "la",
    "debilidad": "la",
    "alarma": "la",
    "electrónica": "la",
    "falta": "la",
    "calidad": "la",
    "familia": "la",
    "gota": "la",
    "diente": "el",  # el diente!
    "semana": "la",
    "zeta": "la",
    "vida": "la",
    "diosa": "la",
    "divorcio": "el",
    "granito": "el",
    "grito": "el",
    "mármol": "el",
    "sollozo": "el",
    "rehén": "el",
    "central": "la",
    "trasero": "el",
    "payo": "el",
    "Río": "el",
    "siamés": "el",
    "soldado": "el",
}

conn = sqlite3.connect(DB_FILE)
c = conn.cursor()

updated = 0
for word, article in ARTICLES.items():
    c.execute("UPDATE words SET article = ? WHERE word = ? AND article = ''", (article, word))
    updated += c.rowcount

conn.commit()

# Verify
c.execute("SELECT count(*) FROM words WHERE article != '' AND is_ignored = 0")
total_with_article = c.fetchone()[0]
c.execute("SELECT count(*) FROM words WHERE article = '' AND is_ignored = 0")
total_without = c.fetchone()[0]

print(f"Updated {updated} words with articles")
print(f"Words with article: {total_with_article}")
print(f"Words without article (not nouns): {total_without}")

# Spot check
c.execute("SELECT word, article, translation FROM words WHERE article != '' ORDER BY RANDOM() LIMIT 10")
print("\nSample:")
for w, a, t in c.fetchall():
    print(f"  {a} {w} — {t}")

conn.close()
